# Input path
input_path: '/dataset/other-data/RubberWhale/'

# Feature detector parameters
max_corners: 500
quality_level: 0.01
min_distance: 10
block_size: 3

# Lucas-Kanade optical flow parameters
window_size: 21
max_level: 3
max_iterations: 30
epsilon: 0.01

# RANSAC parameters
ransac_threshold: 3.0
