# Input path
input_path: '/dataset/slow_traffic_small.mp4'

# Feature detector parameters
max_corners: 100
quality_level: 0.3
min_distance: 7
block_size: 7

# Lucas-Kanade optical flow parameters
window_size: 15
max_level: 2
max_iterations: 10
epsilon: 0.03

# RANSAC parameters
ransac_threshold: 3.0
