# Input path
input_path: '/dataset/other-data/RubberWhale/'

# Horn-Schunck tuning parameters
alpha: 10.0
num_iterations: 5
epsilon: 0.01

# Gaussian pyramid parameters
num_levels: 2
pyramid_scale: 0.5
