# Input path
input_path: '/dataset/Forest_15_3b_Videvo.mp4'

# Output Path
output_path: 'flow_lk.flo'

# Feature detector parameters
max_corners: 100
quality_level: 0.3
min_distance: 7
block_size: 7

# Lucas-Kanade optical flow parameters
window_size: 15
max_level: 2
max_iterations: 10
epsilon: 0.03

# RANSAC parameters
ransac_threshold: 3.0
